const mongoose = require("../connect");
const Schema = require("mongoose").Schema;
var properitySchema = {
    codigo : String,
    adVendedor : Number,
    codigoInmobiliaria : String,
    STATUS : String,
    idtipo : Number,
    tipo : String,
    oferta : String,
    estado : String,
    idCiudad : Number,
    idTipoInmueble : Number,
    idTipoOferta : Number,
    region : String,
    ubicacion : String,
    zona : String,
    idZona : Number,
    direccion : String,
    moneda : String,
    monedaIso : String,
    precio : String,
    precioIso : Number,
    descripcion : String,
    fecentrega : String,
    supterreno : String,
    servicios : String,
    amurallado : String,
    anioconstruccion : String,
    desHabitacion : String,
    desBano : String,
    supconstruida : String,
    supterraza : String,
    numDormitorios : String,
    dormitorios : String,
    numBanios : String,
    banios : String,
    piso : String,
    elevador : String,
    baulera : String,
    piscina : String,
    parqueos : String,
    numParqueos : String,
    amoblado : String,
    fecpublicacion : Date,
    latitud : String,
    longitud : String,
    bshow : Boolean,
    bmipublic : Boolean,
    rating : Number,
    href : String,
    hrefPago : String,
    hrefEdit : String,
    ogUrl : String,
    ogTitle : String,
    ogDescription : String,
    ogPicture : String,
    hrefPageShort : String,
    idPlanAgente : String,
    IIP : Number,
    PLNC : String,
    PLN : String,
    ICO : String,
    bIsPlanElite : Boolean,
    bIsMine : Boolean,
    bCanSeePlan : Boolean,
    bIsNotCompany : Boolean,
    bIsCompanyCompanyInfo : Boolean,
    bIsCompanyContactInfo : Boolean,
    images : [{type : Schema.ObjectId,ref : "images"}],
    video : [{type : Schema.ObjectId,ref : "video"}],
    favotiros : Number,
    bHasNetwork : Boolean
};
var properity = mongoose.model("properity", properitySchema);
module.exports = properity;